General fixes
ZerioDev/Music-bot pull request #272
Opened 2023-04-09 23:35 UTC by Alphaegen

- Swapped resume/pause messages because of inverted order
- Added try/catch to lyrics button to prevent crash with Cloudflare captcha

Also reformatted some of the code. Fixed usage of spacing.

2023-04-10 16:23 UTC, Alphaegen commented
Also added a history command now, by simply using the history from the `discord-player`.

2023-04-10 22:29 UTC, Alphaegen commented
- Added `@distube/ytdl-core` as the default, since it is preferred over `play-dl`. 
- Also made it usable without needing a .env, which would prevent any `Could not extract stream for this track` errors from occurring no matter the system. (they still occurred on servers with `play-dl` if no .env was used)
- Added a debugging command (might not be useful now, but probably will be later.

2023-04-11 05:18 UTC, revot334 commented on main.js
please remove debugging

2023-04-11 05:19 UTC, revot334 commented on package.json
remove not need with yarn

2023-04-11 05:21 UTC, revot334 requested changes
please see comments

2023-04-11 07:57 UTC, Alphaegen commented on main.js
Debugging has been removed

2023-04-11 09:23 UTC, dragiez commented on src/buttons/lyrics.js
where have u defined genius?

2023-04-12 03:23 UTC, merged

2023-04-12 03:34 UTC, revot334 commented
please fix node start script dose not work