Fixed Youtube Extractor error
ZerioDev/Music-bot pull request #338
Opened 2024-10-23 17:22 UTC by dev-shashwatt

This update addresses instability issues caused by the previous YouTube extractor. I have replaced the existing implementation in main.js with the new YoutubeiExtractor, which is more reliable. Users will need to run yarn install to install the new extractor before starting the bot as usual. This change aims to enhance performance and improve user experience.

2024-10-24 05:59 UTC, revot334 requested changes
Please review feed back

2024-10-24 05:59 UTC, revot334 commented on CHANGES DONE.txt
remove this file and add the command to the right place in the readme (aka in the setup)

2024-10-24 05:59 UTC, revot334 commented on .env.example
add back

2024-10-24 05:59 UTC, revot334 commented on main.js
looks great
also add new package to the package.json

2024-10-24 08:17 UTC, dev-shashwatt commented on CHANGES DONE.txt
okay i added it in the package.json so that it gets auto installed with the other packages when the user does yarn install

2024-10-27 05:03 UTC, revot334 approved these changes

2024-10-27 05:03 UTC, merged